version: 2

jobs:

  build:
    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx1g"
    working_directory: ~/workspace
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle" }}
      - run:
          command: git tag 2.5.0-SNAPSHOT
      - run:
          command: ./gradlew --no-daemon clean javadoc
      - run:
          # run static analysis tasks standalone to avoid OOME in CircleCI
          command: ./gradlew --max-workers=1 --no-daemon analyze
      - run:
          command: ./gradlew --no-daemon -PmaxParallelForks=1 build
      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          command: mkdir ~/test-results
      - run:
          command: find ~/workspace -type f -regex ".*/test-results/.*xml" -exec ln {} ~/test-results/ \;
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results
      - store_artifacts:
          path: build/libs
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
